platform :ios, '10.0'

workspace 'example'

target 'example' do
  pod 'Stripe', '~> 10.1.0'
end

target 'TPSStripe' do
  project '../node_modules/tipsi-stripe/ios/TPSStripe'
  pod 'Stripe', '~> 10.1.0'
end
