# Use iOS 11 and above
platform :ios, '11.0'

# Specify Workspace
workspace 'example'

target 'example' do
  # Stripe
  pod 'Stripe', '~> 21.3.1'

  # Install additional dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
end
